### PR TITLE
Add support for custom working directory

### LINKED ISSUE #16: Support specifying the configuration directory
Right now, the mixin has the configuration directory hard coded. I think that we should allow users to specify this for a few reasons:

1.) The JSON schema include that, so tooling can prompt users, so there is less "magic" to know
2.) We can enable people to use the mixin more than once in a single bundle (for complex scenarios)
3.) In general it just gives people more flexibility.

### PR DESCRIPTION
**Pull request by ThorstenHans**
With this PR, users can specify a custom working directory for theit Terraform project. 

- [x] Tests
- [x] Docs (Readme)

### CODE REVIEW

**Comment by carolynvs** [comment]
I have removed the comment that this fixes #16. For #16 we should first update the builder library so that it supports changing the workding directory, and then use that in the terraform mixin.

https://github.com/getporter/porter/issues/1403

**Comment by vdice** [comment]
I'm unclear whether we want this change even if/when we add changes to fix #16 .  The changeset here looks good to me, if we wish to proceed with both.

**Comment by carolynvs** [comment]
Now that we have built-in support for setting the working directory on a mixin, here's how a mixin can support this too:

1. Update the dependency on porter in their go.mod file to v0.38.0+
1. Add a field "dir" to the mixin step instruction, just like the exec mixin
    https://github.com/getporter/porter/blob/aa542e4cefe02605ffc9667b8af65cbdcccf022d/pkg/exec/action.go#L102
2. Implement the updated executable step interface 
    https://github.com/getporter/porter/blob/aa542e4cefe02605ffc9667b8af65cbdcccf022d/pkg/exec/action.go#L138-L140

**Comment by vdice** [comment]
@ThorstenHans now that it will be possible to add support in this mixin for the standardized method of setting the working dir per step, do we still wish to add this functionality at the mixin config level?

**Comment by ThorstenHans** [comment]
Obviously, the mixin should adopt the feature from porter instead of adding support for working directory by itself.

**Comment by ThorstenHans** [comment]
Should I create a dedicated PR (for updating the porter dep) and add an example there or could I reuse this PR instead

**Comment by vdice** [comment]
@ThorstenHans Although I might have a slight preference towards the creation of a new PR, I'll leave it up to you - whichever is most convenient.

**Comment by ThorstenHans** [comment]
@vdice that's fine for me I'll close this one 👍

**Pull request closed without merging**
